export default {
  GET_BEER: "GET_BEER",
  GET_BEER_ERROR: "GET_BEER_ERROR",
  GET_BEER_PENDING: "GET_BEER_PENDING",
  GET_BEER_SUCCESS: "GET_BEER_SUCCESS",
  UPDATE_BEER: "UPDATE_BEER",
  UPDATE_BEER_ERROR: "UPDATE_BEER_ERROR",
  UPDATE_BEER_SUCCESS: "UPDATE_BEER_SUCCESS",
  GET_BEER_NAMES: "GET_BEER_NAMES",
  GET_BEER_NAMES_PENDING: "GET_BEER_NAMES_PENDING",
  GET_BEER_NAMES_SUCCESS: "GET_BEER_NAMES_SUCCESS"
};
