export default {
  GET_BEER: "GET_BEER",
  GET_BEER_ERROR: "GET_BEER_ERROR",
  GET_BEER_PENDING: "GET_BEER_PENDING",
  GET_BEER_SUCCESS: "GET_BEER_SUCCESS", // need
  UPDATE_BEER: "UPDATE_BEER", // need
  UPDATE_BEER_ERROR: "UPDATE_BEER_ERROR",
  UPDATE_BEER_SUCCESS: "UPDATE_BEER_SUCCESS"
};
