export default {
  GET_BREWS_PENDING: "GET_BREWS_PENDING",
  GET_BREWS_ERROR: "GET_BREWS_ERROR",
  GET_BREWS_SUCCESS: "GET_BREWS_SUCCESS",
  GET_BREWS: "GET_BREWS",
  CHANGE_RATING: "CHANGE_RATING",
  CHANGE_RATING_SUCCESS: "CHANGE_RATING_SUCCESS",
  CHANGE_RATING_ERROR: "CHANGE_RATING_ERROR",
  GET_FILTERED_BREWS: "GET_FILTERED_BREWS",
  GET_FILTERED_BREWS_SUCCESS: "GET_FILTERED_BREWS_SUCCESS",
  GET_FILTERED_BREWS_PENDING: "GET_FILTERED_BREWS_ERROR"
};
