export default {
  ADD_FAVORITE_SUCCESS: "ADD_FAVORITE_SUCCESS",
  ADD_FAVORITE_ERROR: "ADD_FAVORITE_ERROR",
  REMOVE_FAVORITE_SUCCESS: "REMOVE_FAVORITE_SUCCESS",
  REMOVE_FAVORITE_ERROR: "REMOVE_FAVORITE_ERROR",
  GET_FAVORITES_SUCCESS: "GET_FAVORITES_SUCCESS",
  GET_FAVORITES_ERROR: "GET_FAVORITES_ERROR"
};
