export default {
  GET_BREW: "GET_BREW",
  GET_BREW_PENDING: "GET_BREW_PENDING",
  GET_BREW_ERROR: "GET_BREW_ERROR",
  GET_BREW_SUCCESS: "GET_BREW_SUCCESS",
  GET_BEER: "GET_BEER",
  GET_BEER_PENDING: "GET_BEER_PENDING",
  GET_BEER_ERROR: "GER_BEER_ERROR",
  GET_BEER_SUCCESS: "GET_BEER_SUCCESS",
  CHANGE_RATING: "CHANGE_RATING",
  CHANGE_RATING_SUCCESS: "CHANGE_RATING_SUCCESS",
  CHANGE_RATING_ERROR: "CHANGE_RATING_ERROR"
};
