export default {
  GET_BEER_NAMES: "GET_BEER_NAMES",
  GET_BEER_BY_NAME: "GET_BEER_BY_NAME",
  GET_BREWS_LIST: "GET_BREWS_LIST",
  GET_BREW_BY_ID: "GET_BREW_BY_ID",
  GET_RATING_CHANGE: "GET_RATING_CHANGE",
  GET_ERROR: "GET_ERROR",
  ADD_DELETE_COMMENT: "ADD_DELETE_COMMENT"
};
