export default {
  SAVE_USER_SESSION_SUCCESS: "SAVE_USER_SESSION_SUCCESS",
  SAVE_USER_SESSION_ERROR: "SAVE_USER_SESSION_ERROR",
  SAVE_USER_SESSION_PENDING: "SAVE_USER_SESSION_PENDING",
  LOGOUT_USER: "LOGOUT_USER",
  HIDE_LOGOUT: "HIDE_LOGOUT"
};
