export default {
  SAVE_USER_SESSION: "SAVE_USER_SESSION",
  SAVE_USER_SESSION_SUCCESS: "SAVE_USER_SESSION_SUCCESS",
  SAVE_USER_SESSION_ERROR: "SAVE_USER_SESSION_ERROR",
  SAVE_USER_SESSION_PENDING: "SAVE_USER_SESSION_PENDING",
  CREATE_USER: "CREATE_USER",
  CREATE_USER_ERROR: "CREATE_USER_ERROR",
  CREATE_USER_PENDING: "CREATE_USER_PENDING",
  LOGOUT_USER: "LOGOUT_USER",
  LOGOUT_USER_ERROR: "LOGOUT_USER_ERROR",
  HIDE_LOGOUT: "HIDE_LOGOUT"
};
