export default {
  SAVE_USER_SESSION: "SAVE_USER_SESSION",
  EXIT_USER_SESSION: "EXIT_USER_SESSION",
  HIDE_LOGOUT: "HIDE_LOGOUT",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_ERROR"
};
