export default {
  SAVE_USER_SESSION: "SAVE_USER_SESSION",
  EXIT_USER_SESSION: "EXIT_USER_SESSION",
  HIDE_LOGOUT: "HIDE_LOGOUT",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_ERROR",
  GET_FOREIGN_USER_SUCCESS: "GET_FOREIGN_USER_SUCCESS",
  GET_FAVORITES_SUCCESS: "GET_FAVORITES_SUCCESS",
  REMOVE_FAVORITE_SUCCESS: "REMOVE_FAVORITE_SUCCESS"
};
