export default {
  GET_FAVORITES_ERROR: "GET_FAVORITES_ERROR",
  GET_FAVORITES_PENDING: "GET_FAVORITES_PENDING",
  GET_FAVORITES_SUCCESS: "GET_FAVORITES_SUCCESS",
  ADD_FAVORITE: "ADD_FAVORITE",
  REMOVE_FAVORITE: "REMOVE_FAVORITE"
};
