export default {
  GET_FAVORITES: "GET_FAVORITES",
  GET_FAVORITES_ERROR: "GET_FAVORITES_ERROR",
  GET_FAVORITES_PENDING: "GET_FAVORITES_PENDING",
  GET_FAVORITES_SUCCESS: "GET_FAVORITES_SUCCESS",
  CHANGE_FAVORITES: "CHANGE_FAVORITES"
};
