export default {
  UPDATE_BEER_SUCCESS: "UPDATE_BEER_SUCCESS",
  GET_BEER_SUCCESS: "GET_BEER_SUCCESS",
  GET_BEER_ERROR: "GET_BEER_ERROR",
  SET_VALUE_SUCCESS: "SET_VALUE_SUCCESS",
  SET_BEER_LIST: "SET_BEER_LIST",
  SET_FILTERS: "SET_FILTERS",
  SET_FILTERS_VALUE: "SET_FILTERS_VALUE"
};
