export default {
  UPDATE_BEER_SUCCESS: "UPDATE_BEER_SUCCESS",
  GET_BEER_SUCCESS: "GET_BEER_SUCCESS",
  GET_BEER_ERROR: "GET_BEER_ERROR",
  GET_BEER_NAME_SUCCESS: "GET_BEER_NAME_SUCCESS",
  GET_VALUE_SUCCESS: "GET_VALUE_SUCCESS",
  CONTINUE_BEER_SUCCESS: "CONTINUE_BEER_SUCCESS",
  SET_BEER_LIST: "SET_BEER_LIST",
  SET_FILTERS: "SET_FILTERS",
  FILTER_BEER_SUCCESS: "FILTER_BEER_SUCCESS"
};
